name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    uses: Datadog/action-prebuildify/.github/workflows/build.yml@v1
    with:
      target-name: 'dd_pprof' # target name in binding.gyp
      package-manager: 'npm' # npm or yarn
      cache: true # enable caching of dependencies based on lockfile
