name: ci

on:
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:
    branches: [ main ]

jobs:
  test-js:
    strategy:
      matrix:
        node: [ 12, 14, 16 ]
        os: [ ubuntu-latest, macos-latest, windows-2016 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: node --version
      - run: npm ci --ignore-scripts
      - run: npm run rebuild
      - run: npm run build:js
      - run: npm run test:js
      - name: coverage
        uses: codecov/codecov-action@v1
        with:
          name: actions ${{ matrix.os }} ${{ matrix.node }}

  test-cpp:
    strategy:
      matrix:
        node: [ 12, 14, 16 ]
        os: [ ubuntu-latest, macos-latest, windows-2016 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci --ignore-scripts
      - run: npm run rebuild
      - run: npm run test:cpp

  check-licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci --ignore-scripts
      - run: npm run licenses

  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci --ignore-scripts
      - run: npm run build:js
      - run: npm run lint:js

  lint-cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: pip install cpplint
      - run: npm run lint:cpp

  check-cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install cppcheck
      - run: npm run check:cpp

  cpp:
    needs:
      - lint-cpp
      - check-cpp
      - test-cpp
    runs-on: ubuntu-latest
    steps:
      - run: echo 'cpp success'

  js:
    needs:
      - lint-js
      - test-js
    runs-on: ubuntu-latest
    steps:
      - run: echo 'cpp success'

  all-good:
    needs:
      - js
      - cpp
      - check-licenses
    runs-on: ubuntu-latest
    steps:
      - run: echo '🚀🚀🚀🚀🚀'
