name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        # Switch to windows-latest when we drop 12
        os: [ubuntu-latest, windows-2019, macos-latest]
        node: [ 12, 14, 16, 18 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: node --version
      - run: yarn
      - run: yarn test
      - name: coverage
        uses: codecov/codecov-action@v1
        with:
          name: actions ${{ matrix.os }} ${{ matrix.node }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn
      - run: yarn lint
